apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-game
  namespace: public
  labels:
    app: webapp-game
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapp-game
  template:
    metadata:
      labels:
        app: webapp-game
    spec:
      containers:
        - name: webapp-game
          image: 564496105716.dkr.ecr.us-east-1.amazonaws.com/webapp-game:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 30
            periodSeconds: 30
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
